services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
  Ang3\Bundle\DoctrineCacheInvalidatorBundle\:
    resource: '../../{EventListener,Exception,Factory,Mapping,Resolver}/*'
  
  # LISTENER
  Ang3\Bundle\DoctrineCacheInvalidatorBundle\EventListener\InvalidatorListener:
    arguments:
      $parameters: '%ang3_doctrine_cache_invalidator.parameters%'
      $logger: '@ang3_doctrine_cache_invalidator.logger'
    tags :
      - { name: doctrine.event_listener, event: onFlush }