services:
  # Cache ID resolver service
  ang3_doctrine_invalidator.cache_id_resolver:
    class: Ang3\Bundle\DoctrineCacheInvalidatorBundle\Resolver\CacheIdResolver
    arguments:
      - '@doctrine.orm.entity_manager'
      - '@annotations.reader'
  # Result cache ID invalidator listener
  ang3_doctrine_invalidator.invalidator_listener:
    class: Ang3\Bundle\DoctrineCacheInvalidatorBundle\EventListener\InvalidatorListener
    arguments:
      - '%ang3_doctrine_cache_invalidator.parameters%'
    calls:
        - [setLogger, ['@?ang3_doctrine_cache_invalidator.logger']]
    tags :
      - { name: doctrine.event_listener, event: onFlush }