services:
  # Result cache ID invalidator listener
  ang3_doctrine_invalidator.invalidator_listener:
    class: Ang3\Bundle\DoctrineCacheInvalidatorBundle\EventListener\InvalidatorListener
    arguments:
      - '@annotations.reader'
    calls:
        - [setLogger, ['@?ang3_doctrine_cache_invalidator.logger']]
    tags :
      - { name: doctrine.event_listener, event: onFlush }